<?xml version="1.0" encoding="utf-8"?><Database Name="HIMS.Data" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Data\HIMS.Data.mdf;Integrated Security=True" SettingsObjectName="HIMS.Model.Properties.Settings" SettingsPropertyName="HIMS_DataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OM_OrdersSet" Member="OM_OrdersSet">
    <Type Name="OM_OrdersSet">
      <Column Name="OrderId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateTo" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AM_Accounts_AccountId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>