//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AM_AccountsSet> AM_AccountsSet { get; set; }
        public virtual DbSet<AM_RoleSet> AM_RoleSet { get; set; }
        public virtual DbSet<OM_OrdersSet> OM_OrdersSet { get; set; }
        public virtual DbSet<OM_StateSet> OM_StateSet { get; set; }
        public virtual DbSet<RM_RoomsSet> RM_RoomsSet { get; set; }
        public virtual DbSet<RM_StateSet> RM_StateSet { get; set; }
        public virtual DbSet<RS_Order_RoomsSet> RS_Order_RoomsSet { get; set; }
    }
}
