//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Order_RoomsSet
    {
        public long RS_ID { get; set; }
        public long OrderId { get; set; }
        public long RoomId { get; set; }
        public long OM_Orders_OrderId { get; set; }
        public long RM_Rooms_RoomId { get; set; }
    
        public virtual OM_OrdersSet OM_OrdersSet { get; set; }
        public virtual RM_RoomsSet RM_RoomsSet { get; set; }
    }
}
